service: laravel

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-1
    # The stage of the application, e.g. dev, prod, staging… ('dev' by default)
    stage: prod
    # Environment variables
    environment:
        NODE_ENV: production
        APP_ENV: production # Or use ${sls:stage} if you want the environment to match the stage
        FILESYSTEM_DISK: s3
        FILESYSTEM_DISK_PUBLIC: s3
        AWS_BUCKET: !Ref Storage
        VITE_APP_NAME: ShortenerUrl

        DB_HOST: ${ssm:/shortener-url/db_host}
        DB_PORT: ${ssm:/shortener-url/db_port}
        DB_DATABASE: ${ssm:/shortener-url/db_database}
        DB_USERNAME: ${ssm:/shortener-url/db_username}
        DB_PASSWORD: ${ssm:/shortener-url/db_password}

    iam:
        role:
            statements:
                # Allow Lambda to read and write files in the S3 buckets
                -   Effect: Allow
                    Action: s3:*
                    Resource:
                        - !Sub '${Storage.Arn}' # the storage bucket
                        - !Sub '${Storage.Arn}/*' # and everything inside

plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions # <----- Add the extra Serverless plugin
  - serverless-lift

resources:
    Resources:
        # Create our S3 storage bucket using CloudFormation
        Storage:
            Type: AWS::S3::Bucket

package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'

functions:
    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        runtime: php-83-fpm
        # memorySize: 128 # set to 512M instead of 1024M (the default)
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-83-console
        timeout: 720 # in seconds

constructs:
    website:
        type: server-side-website
        assets:
            '/build/*': public/build
            '/favicon.ico': public/favicon.ico
            '/robots.txt': public/robots.txt
            # add here any file or directory that needs to be served from S3
